Added a navbar component with a Home link.
gitsoufiane/movieApp pull request #4
Opened 2022-06-14 23:07 UTC by thehappyman

- Added the Navbar component with Home link
- Added the Navbar component to the App.js

2022-06-14 23:45 UTC, gitsoufiane commented on src/App.js
> +      <h1 className="text-3xl font-bold underline">Hello world!</h1>;
remove this line

2022-06-14 23:46 UTC, gitsoufiane commented on package.json
> +    "router-dom": "^2.2.9",
remove this line , we don't  use this package

2022-06-14 23:48 UTC, gitsoufiane requested changes
please check my comments

2022-06-17 20:23 UTC, thehappyman commented
Changes are done.
please check them.

2022-06-17 21:17 UTC, gitsoufiane approved these changes
👍

2022-06-17 21:17 UTC, merged